### ISSUE TITLE
Update Contributors Page and Request Additional Information from Contributors | HacktoberFest 2023

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#130]
The current contributors page in the repository could benefit from a major update. We want to enhance the information displayed for each contributor by including a detailed message describing their contributions. Additionally, we should ensure that this information is presented in a visually appealing way on the UI.

## Task : 
Modify the existing JSON file that stores contributor information to include a "message" field for each contributor. This field will contain a detailed description of their contributions, achievements, or any relevant information.
Update the UI to display the new "message" field alongside the contributor's other details in an organized and visually pleasing format.
- [ ] Modify the JSON file with the necessary changes for each contributor.
- [ ] Update the UI to accommodate the new "message" field.
- [ ] Tag all previous contributors on GitHub and kindly request them to fill in their respective "message" fields with detailed information about their contributions.

## Assignees 
@Mohit030802 

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - #{issue_id} Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by Rachit1313** [comment]
Can you assign me this issue?

**Comment by Nayaker** [comment]
Sorry @Rachit1313 it is already completed by a contributor, and I made a new issue just for referencing a new change :)
_You can star mark the repo, soon I am going to add more react basic issues :)_

**Comment by Mohit030802** [comment]
I am interested to work on it

**Comment by Mohit030802** [comment]
Hi @Nayaker I request to ask all contributors to add the contribution in ```src-Components-contributorsData.json``` file.

{
    "user_name": "Your User Name",
    "name": "Your name",
    "description": "About your work and experience while contributing",
    "avatar_url": "Your Github avatar URL",
    "pull_requests": [
      {
        "id": "Your PR ID",
        "title": "Title of that PR",
        "url": "PR URL",
        "created_on": "PR Created on"
      },
	// same if more than one PR
      
    ]
 },

You can refer this template to add.

**Comment by Nayaker** [comment]
I'd like to request all contributors, including @ThorezNS, @sailikpandey22, @Ayushpanditmoto, @JordanAdair, @jinitsuga, @Mohit030802, @dineshigdd, @Lonecloud7, @SurajPrakash24, @Ktn-mariam, @saurabh-sen, @Tsaha11, @lokeshvasnik, @adrianmarinwork, @RajMhatre20, @Ravina-Deogadkar and @jatingodnani to make edits to the file ```client > src > Components > contributorsData.json```

Please add information about your contributions and list your pull requests (PRs) so that we can display them on our website. Additionally, after making these updates, please submit another PR with the title "@{your-username}-contributor-work updated."

**Comment by jatingodnani** [comment]
@Nayaker @Mohit030802 why youbare not talking all data directly from github api

**Comment by Mohit030802** [comment]
Hello @jatingodnani, while we can certainly leverage the GitHub API, we also value and appreciate the personal experiences of our contributors. It would be wonderful if contributors could kindly share their own experiences as well.

**Comment by RajMhatre20** [comment]
Do we still need to add the info?

**Comment by Nayaker** [comment]
If you can - then please add, otherwise later on we will add it manually. @RajMhatre20

**Comment by RajMhatre20** [comment]
Okay i'll add

**Comment by RajMhatre20** [comment]
Should we continue to add more pull request info here after every contribution or it will be added automatically?

**Comment by Nayaker** [comment]
I don't think that can not be automated. I think everyone will have to write after each PR or once a month. 

_If you can suggest an idea for automation, do let me._

**Comment by RajMhatre20** [comment]
Maybe using this?
https://[api.github.com/repos/Nayaker/AlgoListed/contributors](https://api.github.com/repos/Nayaker/AlgoListed/contributors)

**Comment by Nayaker** [comment]
But does this give info about the

**Comment by RajMhatre20** [comment]
https://api.github.com/repos/Nayaker/AlgoListed/pulls

This gives

**Comment by Nayaker** [comment]
Amazing 🚀

**Comment by RajMhatre20** [comment]
Can I work on this?

**Comment by Nayaker** [comment]
Yeah sure take this issue up! @RajMhatre20 

## Issue : Automate contributors page 
_I am assigning the issue to you_

**Comment by RajMhatre20** [comment]
@Nayaker Just a quick question, Do you want me to keep all the people in the contributor work section or only the people who have added their experience working with the repo?

for example:
![image](https://github.com/Nayaker/AlgoListed/assets/68785723/985a5532-4671-437a-90d3-dcee582b757b)

in this case, only Mohit has added the experience, though everyone's pull request will be shown automatically but the description will only be displayed if they add it manually

There are two solutions in my mind
1. Display the people who have added the experience on the top and the rest will be at the bottom
2. Don't display the people who have not added experience at all

If you have any idea other than this tell me, else tell me the given solution number

**Comment by Nayaker** [comment]
@RajMhatre20  I like option 1 - because later on I can manually write the description for they work.
