### ISSUE TITLE
Core Subjects Tracker - "Make the features functional"

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#200]
On `/core-subjects-tracker` - we have all the data that is getting called locally and is shown like this : 

<img width="1440" alt="Screenshot 2023-11-12 at 1 42 05 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/88edf4e0-3205-4b84-9e48-b37879f37246">
<img width="1440" alt="Screenshot 2023-11-12 at 1 42 19 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/01807a8d-6db7-4fce-aaee-35323678bec4">

## Task : 
1. We aim for the user to select the checkbox to advance the progress, and this information will be saved in the local storage.
2. In the second image, you'll notice several options:

    - [x] Users should have the ability to both view and hide the answer; by default, it will be concealed.
    - [x] The information regarding whether the data is solved or marked should be stored in the local storage.
    - [x] The background is changed based on whether the question is completed or is marked.

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this however I don't see this section on the website

**Comment by Nayaker** [comment]
@IrfanSalim Thanks for showing interest, I am assigning this task to you 🚀

_You don't see it on the site because, currently this page is under development and it is not deployed._

**Comment by IrfanSalim** [comment]
Got it @Nayaker 
Thank you!

**Comment by Nayaker** [comment]
Any update @IrfanSalim?

**Comment by IrfanSalim** [comment]
Hey, I have just started working on it, will keep you posted about any updates.

**Comment by IrfanSalim** [comment]
Hey, @Nayaker 

Do you want me to raise a PR individually for each task or one for all features?

**Comment by Nayaker** [comment]
You can do it all at once

**Comment by Nayaker** [comment]
Can you join a meet a sec please https://meet.google.com/wig-crsh-ebt?authuser=0 @IrfanSalim
